% PURPOSE: This file stores all the nouns by category generated by ChatGPT

% AUTHORS: Jiayin Qu, Henning U Voss

%% Fruits

'Fruit1.wav', {'apple' 'banana' 'orange' 'grape' 'pear' 'peach' 'plum' 'kiwi' 'mango' 'papaya'}
'Fruit2.wav', {'pineapple' 'cherry' 'strawberry' 'blueberry' 'raspberry' 'blackberry' 'cranberry' 'watermelon' 'cantaloupe' 'honeydew'}
'Fruit3.wav', {'grapefruit' 'lemon' 'lime' 'tangerine' 'mandarin' 'apricot' 'nectarine' 'pomegranate' 'fig' 'date'} 
'Fruit4.wav', {'prune' 'raisin' 'gooseberry' 'elderberry' 'mulberry' 'boysenberry' 'huckleberry' 'currant' 'persimmon' 'guava'}

%% Vegetables

'Vegetable1.wav', {'carrot' 'potato' 'tomato' 'onion' 'garlic' 'broccoli' 'cauliflower' 'spinach' 'lettuce' 'cabbage'}
'Vegetable2.wav', {'kale' 'zucchini' 'cucumber' 'pepper' 'celery' 'radish' 'turnip' 'beet' 'eggplant' 'squash'}
'Vegetable3.wav', {'pumpkin' 'pea' 'bean' 'corn' 'asparagus' 'artichoke' 'brussels sprout' 'leek' 'mushroom' 'parsnip'}
'Vegetable4.wav', {'rutabaga' 'sweet potato' 'yam' 'okra' 'chard' 'collard' 'mustard green' 'endive' 'bok choy' 'arugula'}

%% Animals

'Animal1.wav', {'dog' 'cat' 'horse' 'cow' 'sheep' 'goat' 'pig' 'chicken' 'duck' 'goose'}
'Animal2.wav', {'turkey' 'rabbit' 'deer' 'elk' 'moose' 'bear' 'wolf' 'fox' 'coyote' 'lion'}
'Animal3.wav', {'tiger' 'leopard' 'cheetah' 'elephant' 'giraffe' 'zebra' 'hippopotamus' 'rhinoceros' 'kangaroo' 'koala'}
'Animal4.wav', {'panda' 'monkey' 'gorilla' 'chimpanzee' 'orangutan' 'baboon' 'lemur' 'sloth' 'armadillo' 'anteater'}

%% Clothing

'Clothing1.wav', {'shirt' 'pants' 'jeans' 'dress' 'skirt' 'blouse' 'jacket' 'coat' 'sweater' 'hoodie'}
'Clothing2.wav', {'t-shirt' 'shorts' 'cap' 'hat' 'scarf' 'glove' 'mittens' 'socks' 'shoes' 'boots'}
'Clothing3.wav', {'sandals' 'slippers' 'suit' 'tie' 'belt' 'underwear' 'bra' 'panties' 'boxers' 'briefs'}
'Clothing4.wav', {'sneakers' 'flip-flops' 'raincoat' 'windbreaker' 'overalls' 'leggings' 'stockings' 'tights' 'robe' 'pajamas'}

%% Tools

'Tool1.wav', {'hammer' 'screwdriver' 'wrench' 'pliers' 'saw' 'drill' 'tape measure' 'level' 'chisel' 'file'}
'Tool2.wav', {'sandpaper' 'vise' 'clamp' 'utility knife' 'scissors' 'handsaw' 'hacksaw' 'socket wrench' 'ratchet' 'allen wrench'}
'Tool3.wav', {'adjustable wrench' 'pipe wrench' 'crescent wrench' 'torque wrench' 'pliers' 'wire cutters' 'crimping tool' 'c-clamp' 'bar clamp' 'spring clamp'}
'Tool4.wav', {'bench vise' 'anvil' 'mallet' 'sledgehammer' 'trowel' 'putty knife' 'paintbrush' 'roller' 'drop cloth'  'needle nose pliers'} )

%% Electronics

'Electronics1.wav', {'television' 'radio' 'computer' 'laptop' 'tablet' 'smartphone' 'camera' 'camcorder' 'printer' 'scanner'}
'Electronics2.wav', {'monitor' 'keyboard' 'mouse' 'trackpad' 'speaker' 'microphone' 'headphones' 'earbuds' 'charger' 'battery'}
'Electronics3.wav', {'remote control' 'router' 'modem' 'flash drive' 'hard drive' 'memory card' 'bluetooth' 'adapter' 'HDMI cable' 'USB cable'}
'Electronics4.wav', {'projector' 'smartwatch' 'fitness tracker' 'e-reader' 'digital frame' 'game console' 'joystick' 'game controller' 'VR headset' 'drone'}

%% Vehicles

'Vehicle1.wav', {'car' 'truck' 'bus' 'motorcycle' 'bicycle' 'scooter' 'skateboard' 'rollerblade' 'boat' 'ship'}
'Vehicle2.wav', {'yacht' 'sailboat' 'canoe' 'kayak' 'jet ski' 'submarine' 'airplane' 'helicopter' 'glider' 'hot air balloon'}
'Vehicle3.wav', {'blimp' 'spaceship' 'rocket' 'space shuttle' 'hovercraft' 'tank' 'bulldozer' 'crane' 'tractor' 'forklift'}
'Vehicle4.wav', {'golf cart' 'snowmobile' 'ATV' 'RV' 'camper' 'minivan' 'sedan' 'SUV' 'convertible' 'limousine'}

%% Furniture

'Furniture1.wav', {'sofa' 'couch' 'chair' 'recliner' 'rocking chair' 'loveseat' 'bench' 'stool' 'ottoman' 'table'}
'Furniture2.wav', {'dining table' 'coffee table' 'side table' 'desk' 'writing desk' 'computer desk' 'bookshelf' 'cabinet' 'wardrobe' 'dresser'}
'Furniture3.wav', {'nightstand' 'bed' 'bunk bed' 'futon' 'headboard' 'footboard' 'bed frame' 'mattress' 'box spring' 'chest'}
'Furniture4.wav', {'hutch' 'sideboard' 'buffet' 'china cabinet' 'curio cabinet' 'TV stand' 'entertainment center' 'bar stool' 'patio furniture' 'bean bag'}

%% Jobs

'Job1.wav', {'teacher' 'doctor' 'nurse' 'engineer' 'architect' 'lawyer' 'accountant' 'chef' 'cook' 'waiter'}
'Job2.wav', {'waitress' 'cashier' 'manager' 'salesperson' 'police officer' 'firefighter' 'paramedic' 'scientist' 'researcher' 'pharmacist'}
'Job3.wav', {'dentist' 'veterinarian' 'electrician' 'plumber' 'carpenter' 'mechanic' 'pilot' 'flight attendant' 'bus driver' 'taxi driver'}
'Job4.wav', {'truck driver' 'construction worker' 'welder' 'painter' 'artist' 'musician' 'actor' 'writer' 'journalist' 'photographer'}

%% Sports

'Sport1.wav', {'soccer' 'basketball' 'baseball' 'football' 'tennis' 'golf' 'hockey' 'volleyball' 'swimming' 'running'}
'Sport2.wav', {'cycling' 'boxing' 'wrestling' 'gymnastics' 'skiing' 'snowboarding' 'surfing' 'skateboarding' 'horseback riding' 'fencing'}
'Sport3.wav', {'archery' 'badminton' 'table tennis' 'rugby' 'cricket' 'lacrosse' 'rowing' 'sailing' 'diving' 'triathlon'}
'Sport4.wav', {'marathon' 'kayaking' 'canoeing' 'rock climbing' 'mountaineering' 'hiking' 'camping' 'fishing' 'hunting' 'paintball'}

%% Countries

'Country1.wav', {'United States' 'Canada' 'Mexico' 'Brazil' 'Argentina' 'Chile' 'Colombia' 'Peru' 'Venezuela' 'Uruguay'}
'Country2.wav', {'Paraguay' 'Bolivia' 'Ecuador' 'Guyana' 'Suriname' 'France' 'Germany' 'Italy' 'Spain' 'Portugal'} 
'Country3.wav', {'United Kingdom' 'Ireland' 'Netherlands' 'Belgium' 'Luxembourg' 'Switzerland' 'Austria' 'Denmark' 'Sweden' 'Norway'}
'Country4.wav', {'Finland' 'Iceland' 'Russia' 'China' 'Japan' 'South Korea' 'North Korea' 'India' 'Pakistan' 'Bangladesh'}

%% Drinks

'Drink1.wav', {'water' 'juice' 'milk' 'coffee' 'tea' 'coke' 'beer' 'wine' 'whiskey' 'vodka'}
'Drink2.wav', {'rum' 'gin' 'tequila' 'champagne' 'cider' 'lemonade' 'iced tea' 'smoothie' 'milkshake' 'latte'}
'Drink3.wav', {'cappuccino' 'espresso' 'mocha' 'americano' 'frappuccino' 'hot chocolate' 'apple juice' 'orange juice' 'grape juice' 'cranberry juice'}
'Drink4.wav', {'tomato juice' 'carrot juice' 'ginger beer' 'pineapple juice' 'soda' 'coconut water' 'sports drink' 'energy drink' 'shake' 'herbal tea'}
